name: ai_game_generator_pro
description: Complete AI-powered mobile game - KEYSTORE ISSUE FIXED
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true