workflows:
  flutter-workflow:
    name: Flutter Mobile App Build with GitHub Releases
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      flutter: stable
      java: 17
      vars:
        GITHUB_TOKEN: $GITHUB_TOKEN
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/flutter_game/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd flutter_game
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd flutter_game
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd flutter_game
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          cd flutter_game
          flutter build apk --release
      - name: Build AAB with Flutter
        script: |
          cd flutter_game
          flutter build appbundle --release
      - name: Build iOS with Flutter (unsigned)
        script: |
          cd flutter_game
          flutter build ios --release --no-codesign
      - name: Create GitHub Release with APK Upload
        script: |
          # Get version from pubspec.yaml
          VERSION=$(grep '^version:' flutter_game/pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Create release using GitHub API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_FULLNAME/releases \
            -d "{
              \"tag_name\": \"v$VERSION-build-$CM_BUILD_ID\",
              \"target_commitish\": \"main\",
              \"name\": \"🎮 AI Game Generator Pro v$VERSION (Build $CM_BUILD_ID)\",
              \"body\": \"🎮 **AI Game Generator Pro Mobile Release**\\n\\n📱 **What's Included:**\\n- ✅ **Android APK** (Ready to install on Android devices)\\n- ✅ **Android AAB** (Google Play Store ready)\\n- ✅ **iOS Build** (Unsigned iOS build files)\\n\\n🚀 **Features:**\\n- Complete Flutter game with Flame engine\\n- Touch controls and collision detection\\n- Professional mobile game architecture\\n- Score tracking and game mechanics\\n- Responsive design for all screen sizes\\n\\n📦 **Build Information:**\\n- **Build ID:** $CM_BUILD_ID\\n- **Flutter Version:** $(flutter --version | head -n 1)\\n- **Build Date:** $BUILD_DATE\\n- **Platform:** iOS + Android\\n\\n📲 **Installation Instructions:**\\n1. **Android:** Download the APK file below and install on your device\\n2. **iOS:** Use the unsigned build for development/testing\\n\\n**🎯 Download the APK below to play the game on Android!**\",
              \"draft\": false,
              \"prerelease\": false
            }")
          
          # Extract release ID
          RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r '.id')
          echo "Created release with ID: $RELEASE_ID"
          
          # Upload APK to GitHub Release
          echo "Uploading APK to GitHub Release..."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @flutter_game/build/app/outputs/flutter-apk/app-release.apk \
            "https://uploads.github.com/repos/$REPO_FULLNAME/releases/$RELEASE_ID/assets?name=AIGameGeneratorPro-v$VERSION-Android.apk"
          
          # Upload AAB to GitHub Release
          echo "Uploading AAB to GitHub Release..."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @flutter_game/build/app/outputs/bundle/release/app-release.aab \
            "https://uploads.github.com/repos/$REPO_FULLNAME/releases/$RELEASE_ID/assets?name=AIGameGeneratorPro-v$VERSION-GooglePlay.aab"
          
          echo "✅ GitHub Release created successfully with all mobile app files!"
          echo "🔗 Release URL: https://github.com/$REPO_FULLNAME/releases/tag/v$VERSION-build-$CM_BUILD_ID"
    artifacts:
      - flutter_game/build/app/outputs/flutter-apk/*.apk
      - flutter_game/build/app/outputs/bundle/release/*.aab
      - flutter_game/build/ios/Release-iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - hamadixi@tutamail.com
        notify:
          success: true
          failure: true