name: ai_game_generator_pro
description: Complete AI-powered mobile game - KEYSTORE ISSUE FIXED
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.1
  flame_audio: ^2.0.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#42a5f5"